# Generated by Django 5.2 on 2025-04-30 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeverification',
            name='expire_date',
            field=models.DateField(default=datetime.datetime(2025, 4, 30, 13, 37, 41, 86398, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
